package com.masterdns.vpn.util

import com.masterdns.vpn.data.local.ProfileEntity
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

/**
 * Generates TOML config files from a ProfileEntity.
 * Output matches the exact format expected by the Go client core.
 */
object ConfigGenerator {

    private val gson = Gson()

    /**
     * Generate client_config.toml content from a ProfileEntity.
     */
    fun generateConfig(
        profile: ProfileEntity,
        listenPort: Int = 18000,
        listenIpOverride: String? = null,
        protocolOverride: String? = null
    ): String {
        val domains = parseDomains(profile.domains)
        val domainsStr = domains.joinToString(", ") { "\"$it\"" }

        val advanced = parseAdvanced(profile.advancedJson)
        fun cfg(key: String, fallback: String): String {
            val value = advanced[key]?.trim()
            return if (value.isNullOrEmpty()) fallback else value
        }

        return buildString {
            appendLine("# MasterDnsVPN Client Configuration")
            appendLine("# Auto-generated by MasterDnsVPN Android")
            appendLine()

            // Section 1: Tunnel Identity & Security
            appendLine("DOMAINS = [$domainsStr]")
            appendLine("DATA_ENCRYPTION_METHOD = ${profile.encryptionMethod}")
            appendLine("ENCRYPTION_KEY = \"${escapeToml(profile.encryptionKey)}\"")
            appendLine()

            // Section 2: Local Proxy Listener
            appendLine("PROTOCOL_TYPE = \"${protocolOverride ?: profile.protocolType}\"")
            appendLine("LISTEN_IP = \"${escapeToml(listenIpOverride ?: cfg("LISTEN_IP", "127.0.0.1"))}\"")
            appendLine("LISTEN_PORT = $listenPort")
            appendLine("SOCKS5_AUTH = ${cfg("SOCKS5_AUTH", "false")}")
            appendLine("SOCKS5_USER = \"${escapeToml(cfg("SOCKS5_USER", "master_dns_vpn"))}\"")
            appendLine("SOCKS5_PASS = \"${escapeToml(cfg("SOCKS5_PASS", "master_dns_vpn"))}\"")
            appendLine()

            // Section 3: Local DNS Service
            appendLine("LOCAL_DNS_ENABLED = ${cfg("LOCAL_DNS_ENABLED", "false")}")
            appendLine()

            // Section 4: Resolver Selection
            appendLine("RESOLVER_BALANCING_STRATEGY = ${profile.resolverBalancingStrategy}")
            appendLine("PACKET_DUPLICATION_COUNT = ${profile.packetDuplicationCount}")
            appendLine("SETUP_PACKET_DUPLICATION_COUNT = ${profile.setupPacketDuplicationCount}")
            appendLine("STREAM_RESOLVER_FAILOVER_RESEND_THRESHOLD = ${cfg("STREAM_RESOLVER_FAILOVER_RESEND_THRESHOLD", "3")}")
            appendLine("STREAM_RESOLVER_FAILOVER_COOLDOWN = ${cfg("STREAM_RESOLVER_FAILOVER_COOLDOWN", "8.0")}")
            appendLine("RECHECK_INACTIVE_SERVERS_ENABLED = ${cfg("RECHECK_INACTIVE_SERVERS_ENABLED", "true")}")
            appendLine("AUTO_DISABLE_TIMEOUT_SERVERS = ${cfg("AUTO_DISABLE_TIMEOUT_SERVERS", "true")}")
            appendLine("BASE_ENCODE_DATA = ${cfg("BASE_ENCODE_DATA", "false")}")
            appendLine()

            // Section 5: Compression
            appendLine("UPLOAD_COMPRESSION_TYPE = ${profile.uploadCompression}")
            appendLine("DOWNLOAD_COMPRESSION_TYPE = ${profile.downloadCompression}")
            appendLine("COMPRESSION_MIN_SIZE = ${cfg("COMPRESSION_MIN_SIZE", "120")}")
            appendLine()

            // Section 6: MTU Discovery
            appendLine("MIN_UPLOAD_MTU = ${cfg("MIN_UPLOAD_MTU", "40")}")
            appendLine("MIN_DOWNLOAD_MTU = ${cfg("MIN_DOWNLOAD_MTU", "100")}")
            appendLine("MAX_UPLOAD_MTU = ${cfg("MAX_UPLOAD_MTU", "150")}")
            appendLine("MAX_DOWNLOAD_MTU = ${cfg("MAX_DOWNLOAD_MTU", "500")}")
            appendLine("MTU_TEST_RETRIES = ${cfg("MTU_TEST_RETRIES", "2")}")
            appendLine("MTU_TEST_TIMEOUT = ${cfg("MTU_TEST_TIMEOUT", "2.0")}")
            appendLine("MTU_TEST_PARALLELISM = ${cfg("MTU_TEST_PARALLELISM", "32")}")
            appendLine("SAVE_MTU_SERVERS_TO_FILE = ${cfg("SAVE_MTU_SERVERS_TO_FILE", "false")}")
            appendLine()

            // Section 7: Runtime Workers
            appendLine("TUNNEL_READER_WORKERS = ${cfg("TUNNEL_READER_WORKERS", "2")}")
            appendLine("TUNNEL_WRITER_WORKERS = ${cfg("TUNNEL_WRITER_WORKERS", "2")}")
            appendLine("TUNNEL_PROCESS_WORKERS = ${cfg("TUNNEL_PROCESS_WORKERS", "2")}")
            appendLine("TUNNEL_PACKET_TIMEOUT_SECONDS = ${cfg("TUNNEL_PACKET_TIMEOUT_SECONDS", "10.0")}")
            appendLine("TX_CHANNEL_SIZE = ${cfg("TX_CHANNEL_SIZE", "8192")}")
            appendLine("RX_CHANNEL_SIZE = ${cfg("RX_CHANNEL_SIZE", "12288")}")
            appendLine("RESOLVER_UDP_CONNECTION_POOL_SIZE = ${cfg("RESOLVER_UDP_CONNECTION_POOL_SIZE", "128")}")
            appendLine()

            // Section 8: ARQ
            appendLine("ARQ_WINDOW_SIZE = ${cfg("ARQ_WINDOW_SIZE", "600")}")
            appendLine("ARQ_INITIAL_RTO_SECONDS = ${cfg("ARQ_INITIAL_RTO_SECONDS", "1")}")
            appendLine("ARQ_MAX_RTO_SECONDS = ${cfg("ARQ_MAX_RTO_SECONDS", "5.0")}")
            appendLine("ARQ_MAX_DATA_RETRIES = ${cfg("ARQ_MAX_DATA_RETRIES", "1200")}")
            appendLine("ARQ_DATA_NACK_INITIAL_DELAY_SECONDS = ${cfg("ARQ_DATA_NACK_INITIAL_DELAY_SECONDS", "0.4")}")
            appendLine("ARQ_DATA_NACK_REPEAT_SECONDS = ${cfg("ARQ_DATA_NACK_REPEAT_SECONDS", "1.0")}")
            appendLine("ARQ_INACTIVITY_TIMEOUT_SECONDS = ${cfg("ARQ_INACTIVITY_TIMEOUT_SECONDS", "1800.0")}")
            appendLine()

            // Section 9: Logging
            appendLine("LOG_LEVEL = \"${profile.logLevel}\"")
        }
    }

    /**
     * Generate the client_resolvers file content from the profile.
     */
    fun generateResolvers(profile: ProfileEntity): String {
        return buildString {
            appendLine("# MasterDnsVPN Resolvers")
            appendLine("# Auto-generated by MasterDnsVPN Android")
            appendLine()
            profile.resolvers.lines().forEach { line ->
                val trimmed = line.trim()
                if (trimmed.isNotEmpty()) {
                    appendLine(trimmed)
                }
            }
        }
    }

    private fun parseDomains(json: String): List<String> {
        return try {
            val type = object : TypeToken<List<String>>() {}.type
            gson.fromJson<List<String>>(json, type) ?: emptyList()
        } catch (e: Exception) {
            // Fallback: treat as single domain
            listOf(json.trim().removeSurrounding("\""))
        }
    }

    private fun parseAdvanced(json: String): Map<String, String> {
        return try {
            val type = object : TypeToken<Map<String, String>>() {}.type
            gson.fromJson<Map<String, String>>(json, type) ?: emptyMap()
        } catch (e: Exception) {
            emptyMap()
        }
    }

    private fun escapeToml(s: String): String {
        return s.replace("\\", "\\\\").replace("\"", "\\\"")
    }
}
